// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BDrj5wgoouVR2izXCcyNMwpQYNCCOgw',
    appId: '1:450365594667:web:4f8b10652914253142de6e',
    messagingSenderId: '450365594667',
    projectId: 'cafe-info-c67a8',
    authDomain: 'cafe-info-c67a8.firebaseapp.com',
    storageBucket: 'cafe-info-c67a8.firebasestorage.app',
    measurementId: 'G-LY6THW5SF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKQgTYm32ai12g36OYZ7ocB6vzekryYM',
    appId: '1:450365594667:android:2ecf9c69f9f548a942de6e',
    messagingSenderId: '450365594667',
    projectId: 'cafe-info-c67a8',
    storageBucket: 'cafe-info-c67a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYFayngZosI7vjhDBuUFtbw_zBXvrWrI',
    appId: '1:450365594667:ios:65a14fda6342713c42de6e',
    messagingSenderId: '450365594667',
    projectId: 'cafe-info-c67a8',
    storageBucket: 'cafe-info-c67a8.firebasestorage.app',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYFayngZosI7vjhDBuUFtbw_zBXvrWrI',
    appId: '1:450365594667:ios:65a14fda6342713c42de6e',
    messagingSenderId: '450365594667',
    projectId: 'cafe-info-c67a8',
    storageBucket: 'cafe-info-c67a8.firebasestorage.app',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_BDrj5wgoouVR2izXCcyNMwpQYNCCOgw',
    appId: '1:450365594667:web:2dad362c08dd76f742de6e',
    messagingSenderId: '450365594667',
    projectId: 'cafe-info-c67a8',
    authDomain: 'cafe-info-c67a8.firebaseapp.com',
    storageBucket: 'cafe-info-c67a8.firebasestorage.app',
    measurementId: 'G-36R78S9884',
  );
}
